In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
from google.colab import files
files.upload()

Saving StudentsPerformance.csv to StudentsPerformance.csv

{'StudentsPerformance.csv': b"gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score\r\nfemale,group C,some high school,free/reduced,none,0,17,10\r\nfemale,group B,high school,free/reduced,none,8,24,23\r\nfemale,group B,some high school,free/reduced,none,18,32,28\r\nfemale,group B,some college,standard,none,11,38,32\r\nfemale,group C,some college,free/reduced,none,22,39,33\r\nfemale,group B,high school,free/reduced,completed,23,44,36\r\nfemale,group B,some high school,free/reduced,none,24,38,27\r\nfemale,group D,associate's degree,free/reduced,none,26,31,38\r\nfemale,group D,some high school,free/reduced,none,19,34,32\r\nfemale,group C,high school,standard,none,29,29,30\r\nfemale,group C,some high school,free/reduced,completed,29,40,44\r\nfemale,group D,bachelor's degree,free/reduced,none,29,41,47\r\nfemale,group B,some high school,standard,completed,32,51,44\r\nfemale,group C,some college,free/reduced,none,32,39,33\r\nfemale,group E,some high school,free/reduced,none,32,34,38\r\nfemale,group C,high school,free/reduced,none,33,41,43\r\nfemale,group A,high school,free/reduced,completed,34,48,41\r\nfemale,group C,high school,free/reduced,none,34,42,39\r\nfemale,group C,high school,free/reduced,none,26,61,54\r\nfemale,group C,some college,free/reduced,none,25,44,43\r\nfemale,group C,high school,free/reduced,none,22,53,46\r\nfemale,group D,some high school,free/reduced,completed,35,55,60\r\nfemale,group C,high school,free/reduced,none,36,53,43\r\nfemale,group A,associate's degree,free/reduced,none,37,57,56\r\nfemale,group B,some high school,standard,none,37,46,46\r\nfemale,group E,bachelor's degree,standard,none,37,45,38\r\nfemale,group A,some high school,free/reduced,none,38,43,43\r\nfemale,group B,high school,free/reduced,none,38,60,50\r\nfemale,group E,some high school,free/reduced,none,38,49,45\r\nfemale,group C,associate's degree,standard,none,39,64,57\r\nfemale,group D,high school,free/reduced,none,39,52,46\r\nfemale,group B,associate's degree,standard,none,40,48,50\r\nfemale,group C,master's degree,free/reduced,none,40,58,54\r\nfemale,group C,associate's degree,standard,none,40,59,51\r\nfemale,group D,master's degree,free/reduced,none,40,59,54\r\nfemale,group D,some high school,free/reduced,completed,32,65,64\r\nfemale,group A,associate's degree,free/reduced,none,41,51,48\r\nfemale,group B,some high school,standard,none,41,55,51\r\nfemale,group C,high school,free/reduced,none,33,46,43\r\nfemale,group E,high school,free/reduced,none,41,45,40\r\nfemale,group B,high school,standard,none,24,52,51\r\nfemale,group C,high school,free/reduced,none,42,62,60\r\nfemale,group C,some college,free/reduced,completed,34,66,69\r\nfemale,group D,associate's degree,free/reduced,completed,42,61,58\r\nfemale,group E,some college,free/reduced,completed,42,55,54\r\nfemale,group C,bachelor's degree,free/reduced,completed,43,51,54\r\nfemale,group C,some high school,free/reduced,none,43,53,53\r\nfemale,group C,bachelor's degree,free/reduced,none,31,62,61\r\nfemale,group D,associate's degree,free/reduced,none,43,60,58\r\nfemale,group A,some high school,free/reduced,none,44,64,58\r\nfemale,group A,some high school,free/reduced,none,44,45,45\r\nfemale,group C,some high school,free/reduced,none,13,41,51\r\nfemale,group C,bachelor's degree,free/reduced,none,44,63,62\r\nfemale,group C,some high school,standard,completed,44,51,55\r\nfemale,group C,high school,standard,none,44,61,52\r\nfemale,group A,bachelor's degree,standard,none,45,59,64\r\nfemale,group B,some college,free/reduced,none,45,53,55\r\nfemale,group C,some college,free/reduced,completed,45,73,70\r\nfemale,group D,high school,standard,none,45,63,59\r\nfemale,group E,master's degree,free/reduced,none,45,56,54\r\nfemale,group B,high school,free/reduced,completed,46,54,58\r\nfemale,group B,associate's degree,free/reduced,none,46,61,55\r\nfemale,group C,some college,free/reduced,none,46,64,66\r\nfemale,group C,associate's degree,standard,none,46,58,57\r\nfemale,group D,associate's degree,free/reduced,none,46,56,57\r\nfemale,group A,some high school,free/reduced,none,47,59,50\r\nfemale,group B,associate's degree,standard,none,47,49,50\r\nfemale,group C,some high school,standard,none,47,54,53\r\nfemale,group C,bachelor's degree,free/reduced,completed,47,62,66\r\nfemale,group D,associate's degree,free/reduced,none,47,53,58\r\nfemale,group D,master's degree,free/reduced,completed,47,58,67\r\nfemale,group A,some high school,standard,none,48,66,65\r\nfemale,group B,some college,free/reduced,completed,48,56,58\r\nfemale,group B,high school,standard,none,48,62,60\r\nfemale,group C,some high school,free/reduced,none,48,58,52\r\nfemale,group C,some high school,free/reduced,none,48,56,51\r\nfemale,group D,some high school,standard,none,48,58,54\r\nfemale,group D,some high school,free/reduced,none,48,54,53\r\nfemale,group A,some college,free/reduced,none,49,65,55\r\nfemale,group B,associate's degree,standard,none,49,52,54\r\nfemale,group B,some high school,free/reduced,none,49,58,55\r\nfemale,group C,associate's degree,standard,none,49,53,53\r\nfemale,group C,some high school,standard,none,49,63,56\r\nfemale,group D,high school,free/reduced,none,49,57,52\r\nfemale,group D,some college,free/reduced,none,49,58,60\r\nfemale,group D,some college,free/reduced,none,49,65,61\r\nfemale,group A,master's degree,standard,none,50,53,58\r\nfemale,group A,master's degree,free/reduced,none,50,67,73\r\nfemale,group B,high school,free/reduced,none,50,67,63\r\nfemale,group B,high school,standard,none,50,53,55\r\nfemale,group B,some college,standard,completed,50,64,66\r\nfemale,group C,high school,free/reduced,completed,50,66,64\r\nfemale,group C,some high school,free/reduced,completed,50,60,60\r\nfemale,group C,bachelor's degree,free/reduced,none,50,60,59\r\nfemale,group D,some high school,free/reduced,none,50,64,59\r\nfemale,group E,associate's degree,free/reduced,none,50,56,54\r\nfemale,group E,high school,standard,none,50,50,47\r\nfemale,group A,bachelor's degree,standard,none,51,49,51\r\nfemale,group C,bachelor's degree,free/reduced,completed,51,72,79\r\nfemale,group D,some college,standard,none,51,58,54\r\nfemale,group D,some high school,standard,none,51,63,61\r\nfemale,group D,high school,standard,none,51,66,62\r\nfemale,group E,associate's degree,standard,none,51,51,54\r\nfemale,group B,associate's degree,free/reduced,none,52,76,70\r\nfemale,group B,master's degree,free/reduced,completed,52,70,62\r\nfemale,group B,associate's degree,standard,completed,52,66,73\r\nfemale,group B,bachelor's degree,standard,none,52,65,69\r\nfemale,group B,some high school,free/reduced,completed,52,67,72\r\nfemale,group C,some college,standard,none,52,58,58\r\nfemale,group C,associate's degree,standard,completed,52,59,62\r\nfemale,group C,master's degree,free/reduced,none,52,65,61\r\nfemale,group C,associate's degree,standard,none,52,55,57\r\nfemale,group C,bachelor's degree,standard,completed,52,61,66\r\nfemale,group D,high school,free/reduced,completed,52,57,56\r\nfemale,group D,associate's degree,free/reduced,none,52,59,56\r\nfemale,group D,some college,free/reduced,completed,52,59,65\r\nfemale,group A,high school,free/reduced,completed,53,50,60\r\nfemale,group B,associate's degree,standard,none,53,58,65\r\nfemale,group B,associate's degree,free/reduced,none,53,71,67\r\nfemale,group B,associate's degree,free/reduced,none,53,70,70\r\nfemale,group B,some college,free/reduced,completed,53,66,73\r\nfemale,group C,associate's degree,free/reduced,none,53,61,62\r\nfemale,group C,some college,standard,none,53,62,56\r\nfemale,group C,high school,free/reduced,none,53,72,64\r\nfemale,group C,associate's degree,standard,none,53,62,53\r\nfemale,group D,master's degree,standard,none,53,61,68\r\nfemale,group E,some college,free/reduced,none,53,58,57\r\nfemale,group A,some college,standard,none,54,63,67\r\nfemale,group B,high school,standard,none,54,64,68\r\nfemale,group B,some high school,standard,completed,54,61,62\r\nfemale,group B,associate's degree,free/reduced,none,54,65,65\r\nfemale,group C,associate's degree,free/reduced,none,54,58,61\r\nfemale,group C,high school,standard,none,54,59,62\r\nfemale,group C,some college,standard,none,54,48,52\r\nfemale,group C,some college,standard,none,54,64,65\r\nfemale,group C,master's degree,standard,completed,54,64,67\r\nfemale,group C,associate's degree,standard,none,54,61,58\r\nfemale,group D,master's degree,standard,none,54,60,63\r\nfemale,group A,associate's degree,standard,completed,55,65,62\r\nfemale,group A,high school,standard,none,55,73,73\r\nfemale,group C,some college,standard,none,55,69,65\r\nfemale,group C,some high school,free/reduced,none,55,65,62\r\nfemale,group C,associate's degree,standard,completed,55,72,79\r\nfemale,group D,master's degree,standard,none,55,64,70\r\nfemale,group D,some college,free/reduced,none,55,71,69\r\nfemale,group D,associate's degree,free/reduced,none,55,76,76\r\nfemale,group A,some college,standard,none,56,58,64\r\nfemale,group C,bachelor's degree,standard,completed,56,79,72\r\nfemale,group C,associate's degree,free/reduced,completed,56,68,70\r\nfemale,group D,high school,standard,completed,56,68,74\r\nfemale,group D,high school,standard,none,56,52,55\r\nfemale,group D,associate's degree,free/reduced,none,56,65,63\r\nfemale,group E,master's degree,free/reduced,none,56,72,65\r\nfemale,group B,associate's degree,standard,none,57,69,68\r\nfemale,group B,some high school,standard,none,57,67,72\r\nfemale,group C,associate's degree,free/reduced,none,57,78,67\r\nfemale,group C,associate's degree,standard,completed,57,77,80\r\nfemale,group D,associate's degree,free/reduced,completed,57,74,76\r\nfemale,group D,high school,standard,completed,57,58,64\r\nfemale,group D,associate's degree,standard,completed,57,78,79\r\nfemale,group E,associate's degree,free/reduced,completed,57,68,73\r\nfemale,group E,high school,free/reduced,none,57,58,57\r\nfemale,group E,high school,free/reduced,completed,57,75,73\r\nfemale,group A,some college,standard,none,58,70,67\r\nfemale,group B,master's degree,free/reduced,completed,58,76,78\r\nfemale,group B,some college,free/reduced,none,58,61,66\r\nfemale,group B,high school,standard,completed,58,70,68\r\nfemale,group B,high school,standard,none,58,62,59\r\nfemale,group B,associate's degree,standard,none,58,63,65\r\nfemale,group B,high school,standard,none,58,68,61\r\nfemale,group C,associate's degree,standard,none,58,73,68\r\nfemale,group C,some college,standard,none,58,67,72\r\nfemale,group C,some college,standard,none,58,59,66\r\nfemale,group C,high school,standard,completed,58,75,77\r\nfemale,group D,some college,free/reduced,completed,58,63,73\r\nfemale,group D,some college,free/reduced,none,58,67,62\r\nfemale,group A,some high school,standard,completed,59,85,80\r\nfemale,group A,some high school,free/reduced,none,59,73,69\r\nfemale,group A,bachelor's degree,standard,none,59,72,70\r\nfemale,group B,associate's degree,standard,completed,59,70,66\r\nfemale,group B,some high school,free/reduced,completed,59,63,64\r\nfemale,group C,associate's degree,standard,none,59,66,67\r\nfemale,group C,some college,free/reduced,none,59,62,64\r\nfemale,group C,bachelor's degree,standard,completed,59,64,75\r\nfemale,group C,some college,standard,none,59,71,70\r\nfemale,group C,some high school,standard,completed,59,54,67\r\nfemale,group C,associate's degree,standard,completed,59,73,72\r\nfemale,group C,high school,standard,none,59,72,68\r\nfemale,group C,high school,free/reduced,completed,59,71,65\r\nfemale,group D,some high school,standard,none,59,58,59\r\nfemale,group D,bachelor's degree,standard,none,59,70,73\r\nfemale,group D,some high school,standard,none,59,67,61\r\nfemale,group D,some college,free/reduced,completed,59,78,76\r\nfemale,group D,associate's degree,standard,none,59,70,65\r\nfemale,group D,some high school,standard,none,59,72,80\r\nfemale,group E,high school,standard,completed,59,63,75\r\nfemale,group E,associate's degree,standard,none,59,62,69\r\nfemale,group B,some high school,standard,completed,60,70,70\r\nfemale,group B,some high school,standard,completed,60,70,74\r\nfemale,group B,high school,free/reduced,none,60,72,68\r\nfemale,group C,some college,standard,none,60,72,74\r\nfemale,group C,associate's degree,free/reduced,none,60,75,74\r\nfemale,group C,high school,standard,none,60,68,72\r\nfemale,group C,high school,standard,completed,60,64,74\r\nfemale,group D,some college,free/reduced,none,60,66,70\r\nfemale,group A,some college,free/reduced,none,61,60,57\r\nfemale,group A,high school,standard,none,61,68,63\r\nfemale,group B,associate's degree,standard,completed,61,86,87\r\nfemale,group B,some college,free/reduced,none,61,68,66\r\nfemale,group B,bachelor's degree,standard,none,61,72,70\r\nfemale,group C,high school,standard,none,61,73,63\r\nfemale,group C,high school,standard,none,61,72,70\r\nfemale,group D,some high school,standard,completed,61,74,72\r\nfemale,group D,master's degree,free/reduced,completed,61,71,78\r\nfemale,group E,some college,standard,none,61,64,62\r\nfemale,group E,bachelor's degree,free/reduced,none,61,58,62\r\nfemale,group B,some high school,standard,none,62,64,66\r\nfemale,group B,some college,standard,none,62,67,67\r\nfemale,group B,high school,standard,none,62,62,63\r\nfemale,group C,some college,free/reduced,none,62,67,62\r\nfemale,group C,associate's degree,standard,none,62,74,70\r\nfemale,group C,high school,free/reduced,none,62,67,64\r\nfemale,group C,some college,free/reduced,none,62,72,70\r\nfemale,group C,bachelor's degree,free/reduced,none,62,78,79\r\nfemale,group C,associate's degree,standard,completed,62,76,80\r\nfemale,group C,some college,standard,none,62,69,69\r\nfemale,group D,master's degree,standard,none,62,70,75\r\nfemale,group D,high school,standard,none,62,64,64\r\nfemale,group D,some college,standard,none,62,70,72\r\nfemale,group D,bachelor's degree,free/reduced,none,62,72,74\r\nfemale,group E,master's degree,standard,none,62,68,68\r\nfemale,group E,some college,standard,none,62,73,70\r\nfemale,group B,some college,standard,none,63,65,61\r\nfemale,group B,some high school,free/reduced,completed,63,78,79\r\nfemale,group C,associate's degree,standard,none,63,67,70\r\nfemale,group C,bachelor's degree,standard,none,63,75,81\r\nfemale,group C,some college,standard,completed,63,78,80\r\nfemale,group C,some high school,standard,none,63,73,68\r\nfemale,group C,high school,standard,none,63,69,74\r\nfemale,group C,some college,standard,none,63,74,74\r\nfemale,group C,some college,free/reduced,completed,63,73,71\r\nfemale,group D,some college,free/reduced,completed,63,80,80\r\nfemale,group D,bachelor's degree,free/reduced,none,63,73,78\r\nfemale,group D,some college,standard,none,63,64,67\r\nfemale,group E,some college,standard,completed,63,72,70\r\nfemale,group B,high school,free/reduced,none,64,73,71\r\nfemale,group C,associate's degree,free/reduced,none,64,73,68\r\nfemale,group C,some high school,free/reduced,completed,64,79,77\r\nfemale,group C,some college,free/reduced,completed,64,85,85\r\nfemale,group C,associate's degree,standard,none,64,64,70\r\nfemale,group C,some college,standard,completed,64,82,77\r\nfemale,group D,some high school,standard,completed,64,60,74\r\nfemale,group D,master's degree,standard,none,64,63,66\r\nfemale,group D,some college,free/reduced,none,64,74,75\r\nfemale,group D,associate's degree,standard,none,64,76,74\r\nfemale,group E,bachelor's degree,standard,none,64,73,70\r\nfemale,group E,high school,free/reduced,none,64,62,68\r\nfemale,group A,associate's degree,free/reduced,none,65,85,76\r\nfemale,group A,associate's degree,standard,completed,65,70,74\r\nfemale,group B,high school,standard,none,65,81,73\r\nfemale,group B,some college,free/reduced,completed,65,75,70\r\nfemale,group B,high school,standard,none,65,64,62\r\nfemale,group B,bachelor's degree,standard,completed,65,81,81\r\nfemale,group B,some high school,standard,completed,65,82,78\r\nfemale,group C,bachelor's degree,standard,none,65,72,74\r\nfemale,group C,master's degree,free/reduced,completed,65,81,81\r\nfemale,group C,some high school,free/reduced,none,65,86,80\r\nfemale,group C,some high school,standard,completed,65,74,77\r\nfemale,group C,associate's degree,free/reduced,none,65,77,74\r\nfemale,group C,associate's degree,standard,none,65,76,76\r\nfemale,group C,associate's degree,standard,none,65,77,74\r\nfemale,group C,high school,standard,none,65,69,67\r\nfemale,group C,associate's degree,standard,completed,65,84,84\r\nfemale,group C,some high school,standard,none,65,69,76\r\nfemale,group C,bachelor's degree,standard,none,65,79,81\r\nfemale,group C,some high school,free/reduced,completed,65,76,75\r\nfemale,group D,bachelor's degree,standard,none,65,67,62\r\nfemale,group D,associate's degree,standard,none,65,69,70\r\nfemale,group D,some college,free/reduced,none,65,81,77\r\nfemale,group D,some college,standard,none,65,70,71\r\nfemale,group D,some high school,standard,none,65,82,81\r\nfemale,group D,some high school,standard,completed,65,78,82\r\nfemale,group D,high school,free/reduced,completed,65,61,71\r\nfemale,group E,bachelor's degree,standard,none,65,73,75\r\nfemale,group E,associate's degree,standard,completed,65,75,77\r\nfemale,group B,some high school,standard,none,66,69,68\r\nfemale,group B,bachelor's degree,standard,completed,66,74,81\r\nfemale,group B,high school,standard,none,66,72,70\r\nfemale,group C,high school,standard,none,66,71,76\r\nfemale,group C,bachelor's degree,free/reduced,completed,66,83,83\r\nfemale,group C,high school,free/reduced,none,66,76,68\r\nfemale,group C,bachelor's degree,free/reduced,completed,66,74,81\r\nfemale,group C,associate's degree,standard,none,66,77,73\r\nfemale,group D,some high school,standard,completed,66,78,78\r\nfemale,group E,high school,free/reduced,completed,66,74,78\r\nfemale,group E,associate's degree,standard,none,66,65,69\r\nfemale,group E,some college,standard,completed,66,74,73\r\nfemale,group B,bachelor's degree,standard,none,67,86,83\r\nfemale,group B,some high school,standard,none,67,89,82\r\nfemale,group B,high school,free/reduced,completed,67,78,79\r\nfemale,group B,high school,free/reduced,completed,67,80,81\r\nfemale,group C,bachelor's degree,standard,none,67,69,75\r\nfemale,group C,some college,free/reduced,completed,67,75,70\r\nfemale,group C,associate's degree,standard,completed,67,84,86\r\nfemale,group C,associate's degree,standard,completed,67,84,81\r\nfemale,group C,high school,free/reduced,completed,67,79,84\r\nfemale,group C,some college,standard,completed,67,81,79\r\nfemale,group C,some high school,standard,completed,67,74,77\r\nfemale,group C,bachelor's degree,free/reduced,none,67,75,72\r\nfemale,group D,high school,standard,none,67,72,74\r\nfemale,group D,some high school,free/reduced,none,67,84,84\r\nfemale,group D,some college,free/reduced,completed,67,86,83\r\nfemale,group E,some college,standard,none,67,76,75\r\nfemale,group A,high school,standard,completed,68,80,76\r\nfemale,group B,high school,standard,completed,68,83,78\r\nfemale,group B,associate's degree,free/reduced,completed,68,77,80\r\nfemale,group C,associate's degree,free/reduced,completed,68,67,69\r\nfemale,group C,associate's degree,standard,completed,68,86,84\r\nfemale,group C,associate's degree,standard,completed,68,67,73\r\nfemale,group D,bachelor's degree,standard,completed,68,75,81\r\nfemale,group D,some high school,standard,none,68,71,75\r\nfemale,group D,some college,standard,completed,68,78,77\r\nfemale,group E,some college,standard,none,68,70,66\r\nfemale,group E,associate's degree,standard,none,68,76,67\r\nfemale,group A,some college,standard,none,69,84,82\r\nfemale,group B,high school,standard,completed,69,76,74\r\nfemale,group C,some college,standard,completed,69,90,88\r\nfemale,group C,some high school,standard,none,69,75,78\r\nfemale,group C,some high school,standard,none,69,73,73\r\nfemale,group C,associate's degree,standard,none,69,80,71\r\nfemale,group C,master's degree,st

In [7]:
data = pd.read_csv('StudentsPerformance.csv')

In [8]:
data

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group C,some high school,free/reduced,none,0,17,10
1,female,group B,high school,free/reduced,none,8,24,23
2,female,group B,some high school,free/reduced,none,18,32,28
3,female,group B,some college,standard,none,11,38,32
4,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
995,male,group E,some college,standard,completed,99,87,81
996,male,group A,some college,standard,completed,100,96,86
997,male,group D,some college,standard,completed,100,97,99
998,male,group E,associate's degree,free/reduced,completed,100,100,93
999,male,group E,bachelor's degree,standard,completed,100,100,100

1. Find out how many males and females participated in the test.

In [24]:
data['gender'].value_counts()

female    518
male      482
Name: gender, dtype: int64

2. What do you think about the students' parental level of education?

In [12]:
data1 = data.groupby(['gender','parental level of education'])[['reading score','math score','writing score']].mean()

In [13]:
data1

                                    reading score  math score  writing score
gender parental level of education
female associate's degree               74.120690   65.250000      74.000000
       bachelor's degree                77.285714   68.158730      78.380952
       high school                      68.202128   58.840426      66.691489
       master's degree                  76.805556   66.500000      77.638889
       some college                     73.550847   65.186441      74.050847
       some high school                 69.010989   58.780220      68.285714
male   associate's degree               67.622642   70.962264      65.688679
       bachelor's degree                68.090909   70.581818      67.654545
       high school                      61.284314   64.568627      58.450980
       master's degree                  74.608696   76.130435      72.608696
       some college                     65.212963   69.250000      63.555556
       some high school                 64.431818   67.636364      61.375000

3. Who scores the most on average for math, reading and writing based on
● Gender
● Test preparation course

In [15]:
average = data.groupby(['gender', 'test preparation course'])[['math score', 'reading score', 'writing score']].mean()

In [16]:
average

                                math score  reading score  writing score
gender test preparation course
female completed                 67.108696      77.375000      78.793478
       none                      61.320359      69.955090      68.982036
male   completed                 72.988506      70.793103      70.339080
       none                      66.467532      62.581169      59.551948

4. What do you think about the scoring variation for math, reading and writing
based on
● Gender
● Test preparation course

In [14]:
variation= data.groupby(['gender', 'test preparation course'])[['math score', 'reading score', 'writing score']].var()

In [17]:
variation

                                math score  reading score  writing score
gender test preparation course
female completed                208.173913     161.175546     149.836897
       none                     272.602767     214.241220     225.495172
male   completed                197.098133     185.297987     166.098233
       none                     205.513600     184.843553     181.394687

5. The management needs your help to give bonus points to the top 25% of
students based on their math score, so how will you help the management
to achieve this.

In [19]:
data["math score"].quantile(0.75)
top25 = data[data["math score"] >= 77].sort_values("math score",ascending=False)
top25

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
999,male,group E,bachelor's degree,standard,completed,100,100,100
998,male,group E,associate's degree,free/reduced,completed,100,100,93
997,male,group D,some college,standard,completed,100,97,99
996,male,group A,some college,standard,completed,100,96,86
517,female,group E,associate's degree,standard,none,100,100,100
...,...,...,...,...,...,...,...,...
854,male,group D,some high school,standard,completed,77,68,69
855,male,group E,associate's degree,free/reduced,completed,77,69,68
856,male,group E,some high school,standard,completed,77,76,77
415,female,group B,master's degree,free/reduced,completed,77,97,94
414,female,group A,high school,free/reduced,completed,77,88,85